export const createModeloVeiculoTable = `
  CREATE TABLE IF NOT EXISTS MODELO_VEICULO (
    ID_MODELO VARCHAR(50) PRIMARY KEY,
    NOME_MODELO VARCHAR(50) NOT NULL,
    VALOR_REFERENCIA FLOAT NOT NULL,
    MOTORIZACAO BOOLEAN NOT NULL,
    TURBO BOOLEAN NOT NULL,
    AUTOMATICO BOOLEAN NOT NULL,
    ID_MONTADORA VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_MONTADORA) REFERENCES MONTADORA(ID_MONTADORA) ON DELETE CASCADE
  )
`;