export const createVeiculoTable = `
  CREATE TABLE IF NOT EXISTS VEICULO (
    ID_VEICULO VARCHAR(50) PRIMARY KEY,
    COR VARCHAR(50) NOT NULL,
    ANO_FABRICACAO INT NOT NULL,
    ANO_MODELO INT NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    PLACA VARCHAR(50) NOT NULL,
    VENDIDO BOOLEAN NOT NULL,
    ID_MODELO VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_MODELO) REFERENCES MODELO_VEICULO(ID_MODELO) ON DELETE CASCADE
  )
`;